### ISSUE TITLE
Throw `Out_of_memory` on allocation errors

### ISSUE THREAD

**Issue by DemiMarie** [btj/ocaml-gtk#1]
https://github.com/btj/ocaml-gtk/blob/a8c76fbbe65c091119bb022069f1713a5eeedd01/ml_gobject0.c#L51

It is possible to turn this into an `Out_of_memory` exception, which at least gives a stack trace.

**Comment by DemiMarie** [comment]
(Yes, I know that glib itself crashes on OOM, but the bindings don’t need to crash if throwing an error would be easy.)

**Comment by btj** [comment]
Good suggestion; thanks! Sorry it took me so long to reply!

**Comment by DemiMarie** [comment]
No problem @btj!  You’re welcome!
