### ISSUE TITLE
split up process_namespace() into smaller functions

### ISSUE THREAD

**Issue by martindemello** [btj/ocaml-gtk#6]
The code generator would be easier to read and test if `process_namespace` was broken up a bit (at least into separate functions for methods and signals), and if the `params` array was converted to data objects with meaningful field names (i.e. `params.foo.bar` rather than `params[1][2]`).

I'm happy to do the work if you like the basic idea.

**Comment by btj** [comment]
Good idea! Please go ahead!

**Comment by martindemello** [comment]
great, will work on it :) one thing i'm having a bit of trouble working out from the code - what are the five elements of the `types` tuple?

**Comment by btj** [comment]
Function `ml_to_c_type` returns info about a given introspection type (i.e. a type found in one of the XML files) relevant to the case where a value of that type travels from the OCaml world to the C world (i.e. a method argument or a callback return value). The info is a tuple consisting of five elements:
1. The OCaml type for the procedural bindings
2. A format string that produces the C expression for the OCaml `value` given a C expression for the raw C value. (To understand this, you must read the part in the OCaml manual about interoperating with C.)
3. The C type
4. The OCaml type for the OO bindings
5. A format string that produces the OCaml expression for the unwrapped value given an OCaml expression for the wrapped (OO) value

**Comment by btj** [comment]
So, suitable field names might be `ml_type`, `as_ml_value`, `c_type`, `oo_type`, `unwrap`.

**Comment by btj** [comment]
Many thanks!
